### ISSUE TITLE
show_meshes=False

### ISSUE THREAD

**Issue by tgouss** [pyomeca/BiorbdOptim#16]
``b = BiorbdViz(loaded_model=ocp.nlp[0]["model"], show_meshes=False)
        b.load_movement(x.T)
        b.exec()
``
Casadi cannot open biorbdviz even if show_meshes = False

**Comment by pariterre** [comment]
Fixed in PR (https://github.com/pyomeca/biorbd-viz/pull/24)
Thanks for reporting
