### ISSUE TITLE
Add flexibility option for constraints [ready do be close]

### ISSUE THREAD

**Issue by tgouss** [pyomeca/BiorbdOptim#183]
It would be something like this :

constraints.add(
        Constraint.ALIGN_MARKERS,
        **tol=10e-4**
        instant=Instant.START,
        first_marker_idx=Bow.frog_marker,
        second_marker_idx=violon_string.bridge_marker,
    )

for g :
max_bound=0+tol, min_bound=0-tol

**Comment by tgouss** [comment]
apparently we can already!

**Comment by tgouss** [comment]
it should be add in some examples !

**Comment by pariterre** [comment]
There is already some :)
